export { default as Header } from '@/components/Header.vue'
export { default as Footer } from '@/components/Footer.vue'
export { default as Testimonial } from '@/components/Testimonial.vue'
export { default as Statistic } from '@/components/Statistic.vue'
export { default as Feature } from '@/components/Feature.vue'
export { default as Navigation } from '@/components/Navigation.vue'
export { default as Icons } from '@/components/Icons.vue'